2015-09-10 13:09:24
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/listeners.py", line 31, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 93, in get_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 271, in find_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 159, in find_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1365, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1023, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1019, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError
2015-09-10 13:09:25
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/listeners.py", line 31, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 93, in get_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 271, in find_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 159, in find_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1365, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1023, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1019, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError
2015-09-10 13:09:25
Traceback (most recent call last):
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/threads.py", line 20, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/listeners.py", line 31, in run_with_except
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 93, in get_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 271, in find_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 159, in find_wc_root
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1365, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1262, in run
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1023, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 1019, in do_read
  File "/Users/wbond/Library/Application Support/Sublime Text 3/Packages/SVN/sublimesvn/proc.py", line 723, in read
SVN.sublimesvn.errors.ProcessError
